import { db, ensureSchema, json, failure } from '@/lib/db';
import { statuses, prescription } from '@/lib/orders';
const tableFor=r=>r==='sizal-orders'?'sizal_orders':r==='glass-rx-orders'?'glass_rx_orders':r==='customers'?'customers':r==='products'?'products':r==='pricing-rules'?'pricing_rules':null;
export const runtime='nodejs';
export async function GET(req,{params}){try{await ensureSchema();const {resource,id}=await params;const table=tableFor(resource);if(!table)return failure('Route not found',404);const sql=db();const rows=await sql.query(`SELECT * FROM ${table} WHERE id=$1`,[id]);return rows.length?json(rows[0]):failure('Record not found',404)}catch(e){return failure(e.message,500)}}
export async function PATCH(req,{params}){try{await ensureSchema();const {resource,id}=await params;const table=tableFor(resource);if(!table)return failure('Route not found',404);const body=await req.json();const sql=db();
 if(resource==='customers'){const rows=await sql`UPDATE customers SET name=${String(body.name||'').trim()},mobile=${String(body.mobile||'').replace(/\D/g,'')},updated_at=NOW() WHERE id=${id} RETURNING *`;return rows.length?json(rows[0]):failure('Customer not found',404)}
 if(resource==='pricing-rules'){const rows=await sql`UPDATE pricing_rules SET rule_name=${String(body.rule_name||'').trim()},category=${String(body.category||'').trim()},condition=${String(body.condition||'').trim()},value=${Number(body.value)||0},enabled=${body.enabled!==false},updated_at=NOW() WHERE id=${id} RETURNING *`;return rows.length?json(rows[0]):failure('Rule not found',404)}
 if(resource==='products'){const rows=await sql`UPDATE products SET lens_type=${String(body.lens_type||'').trim()},lens_index=${String(body.lens_index||'').trim()},dia=${String(body.dia||'').trim()},power_range=${String(body.power_range||'').trim()},base_price=${Number(body.base_price)||0},coatings=${JSON.stringify(body.coatings||[])},updated_at=NOW() WHERE id=${id} RETURNING *`;return rows.length?json(rows[0]):failure('Product not found',404)}
 if(body.status&&!statuses.includes(body.status))return failure('Invalid status');const allowed=['status','order_date','customer_name','optical_name','ref_name','ref_mobile','it_code','lens_type','lens_index','dia','power_range','coating','price'];const sets=[],values=[];for(const k of allowed)if(k in body){values.push(body[k]);sets.push(`${k}=$${values.length}`)}for(const k of ['right_eye','left_eye'])if(k in body){values.push(JSON.stringify(prescription(body[k])));sets.push(`${k}=$${values.length}`)}if(!sets.length)return failure('No changes supplied');values.push(id);const rows=await sql.query(`UPDATE ${table} SET ${sets.join(',')},updated_at=NOW() WHERE id=$${values.length} RETURNING *`,values);return rows.length?json(rows[0]):failure('Order not found',404);
}catch(e){return failure(e.message,500)}}
export async function DELETE(req,{params}){try{await ensureSchema();const {resource,id}=await params;const table=tableFor(resource);if(!table)return failure('Route not found',404);const sql=db();await sql.query(`DELETE FROM ${table} WHERE id=$1`,[id]);return json({deleted:true})}catch(e){return failure(e.message,500)}}
